default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: settleup_development

test:
  <<: *default
  database: settleup_test

production:
  <<: *default
  database: settleup_production
  username: settleup
  password: <%= ENV['SETTLEUP_DATABASE_PASSWORD'] %>
